apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-app
  labels:
    app: jenkins-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
        - name: jenkins-k8s-container
          image: yphalak/jenkins-k8s-app:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-service
spec:
  selector:
    app: jenkins-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

