pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'yphalak/jenkins-k8s-app:latest'
        K8S_MANIFEST = 'k8s-deployment.yaml'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/YPhalak/jenkins-k8s-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                kubectl apply -f ${K8S_MANIFEST}
                kubectl rollout status deployment/jenkins-k8s-app
                """
            }
        }
    }
}
